### ISSUE TITLE
Game is stuck on 4 of 8 and won’t continue loading

### ISSUE THREAD

**Issue by Teirusuu** [mazmazz/SRB2-emscripten#24]
Every time I try to start the game, it gets stuck at 4 of 8 and doesn’t continue

**Comment by mazmazz** [comment]
Does the progress bar move? The files are pretty big; it's downloading 80 MB for first run.

**Comment by Teirusuu** [comment]
I got the issue fixed, i had poor network at the time so it downloaded slowly

**Comment by mazmazz** [comment]
Good to hear
