### ISSUE TITLE
Update to v2.2.6

### ISSUE THREAD

**Issue by mazmazz** [mazmazz/SRB2-emscripten#29]
I don't know when or if I will get to this, but if you'd like to try this yourself, feel free to make a merge request. Steps:

1. Add this fork to your remote -- `git remote add web https://github.com/mazmazz/SRB2-emscripten.git`
2. Add Jimita's fork to your remote -- `git remote add jimita https://github.com/Jimita/SRB2.git`
3. Fetch remotes -- `git fetch`
4. Checkout the `emscripten-new` branch -- `git checkout -t web/emscripten-new`
5. Merge Jimita's `android-port-next` branch -- `git merge jimita/android-port-next`
6. Fix the merge conflicts and commit
7. Push to your fork on GitHub, then make a merge request. This will trigger the buildbots which will tell you whether the code compiles.

The merge conflicts involve slight differences in touch controls and the touch menu. Make sure that the touch menu works properly in non-standard resolutions.

If you'd like to build on your own computer, see the `emscripten` directory for instructions.

**Comment by darshytheplayer** [comment]
Hey! It's Kel (aka Khams, the dude you talked to on discord) , just wondering how Web 2.2.8 development is held up. It's been over a month, just wanting an update!

_On the other hand...._  Could you accept the discord friend request from me? Name's kel now.
